packages:
  - packages/*

autoInstallPeers: false

peerDependencyRules:
  ignoreMissing:
    - markdown-it
    - search-insights

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

publicHoistPattern:
  - eslint
  - prettier
