autoInstallPeers: false
peerDependencyRules:
  ignoreMissing:
    - search-insights
    - markdown-it
    - webpack
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
onlyBuiltDependencies:
  - esbuild
packages:
  - packages/*
