name: CI
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm i corepack -g
      - run: corepack enable
      - run: corepack install --global pnpm@latest-10
      - run: pnpm -v
      - run: pnpm install
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm type
      - run: pnpm test --coverage
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
